connector.name=hive
fs.hadoop.enabled=true
hive.config.resources=/opt/hadoop/etc/hadoop/core-site.xml,/opt/hadoop/etc/hadoop/hdfs-site.xml
hive.metastore.uri=thrift://hive-metastore:9083
hive.metastore.authentication.type=KERBEROS
hive.metastore.service.principal=hive/hivemetastore.lakehouse.com@LAKEHOUSE.COM
hive.metastore.client.principal=trino/trino.lakehouse.com@LAKEHOUSE.COM
hive.metastore.client.keytab=/etc/security/keytabs/trino.service.keytab
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.impersonation.enabled=false
hive.hdfs.trino.principal=trino/trino.lakehouse.com@LAKEHOUSE.COM
hive.hdfs.trino.keytab=/etc/security/keytabs/trino.service.keytab
