connector.name=iceberg
fs.hadoop.enabled=true
hive.config.resources=/opt/hadoop/etc/hadoop/core-site.xml,/opt/hadoop/etc/hadoop/hdfs-site.xml
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://iceberg-rest:8181
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.trino.principal=trino/trino.lakehouse.com@LAKEHOUSE.COM
hive.hdfs.trino.keytab=/etc/security/keytabs/trino.service.keytab
