KafkaServer {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    keyTab="/etc/security/keytabs/kafka.service.keytab"
    principal="kafka/kafka.lakehouse.com@LAKEHOUSE.COM"
    storeKey=true;
};

Client {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    keyTab="/etc/security/keytabs/kafka.service.keytab"
    principal="kafka/kafka.lakehouse.com@LAKEHOUSE.COM"
    storeKey=true;
};
