[libdefaults]
    default_realm = LAKEHOUSE.COM
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    udp_preference_limit = 1
    default_ccache_name = FILE:/tmp/krb5cc_%{uid}

[realms]
    LAKEHOUSE.COM = {
        kdc = kerberos
        admin_server = kerberos
        default_domain = lakehouse.com
    }

[domain_realm]
    .lakehouse.com = LAKEHOUSE.COM
    lakehouse.com = LAKEHOUSE.COM
    namenode = LAKEHOUSE.COM
    datanode = LAKEHOUSE.COM
    hivemetastore = LAKEHOUSE.COM
    hiveserver = LAKEHOUSE.COM
    flink-jobmanager = LAKEHOUSE.COM
    flink-taskmanager = LAKEHOUSE.COM
    spark-master = LAKEHOUSE.COM
    spark-worker = LAKEHOUSE.COM
    kafka = LAKEHOUSE.COM
    kerberos = LAKEHOUSE.COM

[logging]
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log
